let templates = [];
let currentTemplate = null;
let renderer;
let queue = [];
let authToken = sessionStorage.getItem("authToken");

document.addEventListener('DOMContentLoaded', () => {
  // Check if the user has a secure token from a previous login in this session
  if (authToken) {
    showApp();
  }
});

// ==========================================
// SECURITY HELPERS
// ==========================================

function getHeaders() {
  return {
    "Content-Type": "application/json",
    "Authorization": `Bearer ${authToken}`
  };
}

function handleApiError(res) {
  if (res.status === 401 || res.status === 403) {
    alert("Session expired or unauthorized. Please log in again.");
    sessionStorage.removeItem("authToken");
    window.location.reload();
    return true;
  }
  return false;
}

// ==========================================
// APP LOGIC
// ==========================================

async function handleLogin() {
  const user = document.getElementById('username').value.trim();
  const pass = document.getElementById('password').value.trim();
  const errorMsg = document.getElementById('loginError');
  const btn = document.querySelector('#loginContainer button');

  if (!user || !pass) return;

  errorMsg.style.display = 'none';
  btn.innerText = 'Authenticating...';
  btn.disabled = true;

  try {
    const res = await fetch("/.netlify/functions/login", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ username: user, password: pass })
    });

    if (res.ok) {
      const data = await res.json();
      authToken = data.token; // Grab the token generated by backend
      sessionStorage.setItem('authToken', authToken); // Save it securely
      showApp();
    } else {
      errorMsg.style.display = 'block';
    }
  } catch (err) {
    console.error("Login failed:", err);
    errorMsg.innerText = "Connection error. Try again.";
    errorMsg.style.display = 'block';
  } finally {
    btn.innerText = 'Login';
    btn.disabled = false;
  }
}

async function showApp() {
  document.getElementById('loginContainer').classList.add('hidden');
  document.getElementById('appContainer').classList.remove('hidden');
  
  // Initialize the renderer and fetch templates ONLY after successful login
  if (!renderer) {
    renderer = new BadgeRenderer(document.getElementById('issueCanvas'));
    await fetchTemplates();
  }
}

async function fetchTemplates() {
  try {
    const res = await fetch("/.netlify/functions/get-templates", {
      headers: getHeaders() // Secure request
    });

    if (handleApiError(res)) return; // Stop if token is invalid

    templates = await res.json();
    
    const select = document.getElementById('templateSelect');
    select.innerHTML = '<option value="">Select a template...</option>';
    templates.forEach(t => {
      select.innerHTML += `<option value="${t.id}">${t.name}</option>`;
    });
  } catch (err) {
    console.error("Failed to fetch templates:", err);
  }
}

function loadSelectedTemplate() {
  const tId = document.getElementById('templateSelect').value;
  currentTemplate = templates.find(t => t.id === tId);
  
  if (!currentTemplate) {
    document.getElementById('batchSettings').classList.add('hidden');
    return;
  }

  document.getElementById('batchSettings').classList.remove('hidden');
  
  // Generate inputs for dynamic placeholders
  const phContainer = document.getElementById('dynamicPlaceholders');
  phContainer.innerHTML = '<strong>Custom Template Fields:</strong><br>';
  
  let csvHeaders = ['email', 'name'];

  currentTemplate.placeholders.forEach(ph => {
    // We already have standard inputs for email and recipientName. 
    // If the template specifically uses "recipientName", we map it directly to p-name later.
    if (ph.key !== 'recipientName') {
      phContainer.innerHTML += `<textarea id="ph-${ph.key}" placeholder="${ph.key}" oninput="updatePreview()"></textarea>`;
      csvHeaders.push(ph.key);
    }
  });

  // Update the CSV helper text dynamically
  document.getElementById('csvFormatGuide').innerHTML = `<small>Required CSV Headers: <b>${csvHeaders.join(', ')}</b></small>`;
  
  updatePreview();
}

// Gathers values from the current input fields
function getCurrentPlaceholderValues(nameInput) {
  const values = { recipientName: nameInput };
  if (!currentTemplate) return values;

  currentTemplate.placeholders.forEach(ph => {
    if (ph.key !== 'recipientName') {
      const el = document.getElementById(`ph-${ph.key}`);
      if (el) values[ph.key] = el.value;
    }
  });
  return values;
}

function updatePreview() {
  if (!currentTemplate) return;
  const name = document.getElementById('p-name').value;
  const values = getCurrentPlaceholderValues(name);
  renderer.render(currentTemplate.image, currentTemplate.placeholders, values);
}

function addParticipant() {
  const email = document.getElementById('p-email').value.trim();
  const name = document.getElementById('p-name').value.trim();
  
  if (!email || !name) return alert("Email and Name are required.");

  const customValues = getCurrentPlaceholderValues(name);

  queue.push({ email, name, values: customValues });
  
  // Clear participant inputs
  document.getElementById('p-email').value = '';
  document.getElementById('p-name').value = '';
  currentTemplate.placeholders.forEach(ph => {
    if (ph.key !== 'recipientName') {
      const el = document.getElementById(`ph-${ph.key}`);
      if (el) el.value = '';
    }
  });

  renderQueue();
  updatePreview(); // Reset preview
}

function removeFromQueue(index) {
  queue.splice(index, 1);
  renderQueue();
}

function renderQueue() {
  document.getElementById('q-count').innerText = queue.length;
  const list = document.getElementById('queueList');
  list.innerHTML = '';
  
  queue.forEach((p, index) => {
    list.innerHTML += `
      <div class="queue-item">
        <span><b>${p.name}</b> (${p.email})</span>
        <span class="remove-btn" onclick="removeFromQueue(${index})">✕</span>
      </div>
    `;
  });
}

// Basic CSV Parser
async function handleCSV(input) {
  const file = input.files[0];
  if (!file) return;

  const text = await file.text();
  const rows = text.split('\n').map(row => row.trim()).filter(row => row);
  
  if (rows.length < 2) return alert("CSV is empty or missing data rows.");

  const headers = rows[0].split(',').map(h => h.trim());
  
  // Parse rows
  // Parse rows
    for (let i = 1; i < rows.length; i++) {
      const cols = rows[i].split(',').map(c => c.trim());
      let email = "", name = "";
      let customValues = {};

      headers.forEach((header, index) => {
        // Grab the cell and convert any literal "\n" strings into actual line breaks
        let cellValue = cols[index] ? cols[index].replace(/\\n/g, '\n') : "";

        if (header === 'email') email = cellValue;
        else if (header === 'name') {
          name = cellValue;
          customValues['recipientName'] = cellValue;
        }
        else {
          customValues[header] = cellValue;
        }
      });

      if (email && name) {
        queue.push({ email, name, values: customValues });
      }
    }

  alert(`${rows.length - 1} participants extracted from CSV.`);
  renderQueue();
  input.value = ''; // Reset file input
}

// Process the Queue
async function issueBulkBadges() {
  if (queue.length === 0) return alert("Queue is empty. Add participants first.");
  
  const badgeName = document.getElementById('badgeName').value.trim();
  const skill = document.getElementById('skill').value.trim();
  const issueMonth = document.getElementById('issueMonth').value.trim();
  const issueYear = document.getElementById('issueYear').value.trim();

  if (!badgeName || !skill || !issueMonth || !issueYear) {
    return alert("Please fill out all Batch Settings (Badge Name, Skill, Month, Year).");
  }

  const btn = document.querySelector('button[onclick="issueBulkBadges()"]');
  btn.innerText = "Issuing... Please wait";
  btn.disabled = true;

  let successCount = 0;

  // We loop through sequentially to avoid overwhelming the frontend/backend limits
  for (const p of queue) {
    const payload = {
      email: p.email,
      recipientName: p.name,
      badgeName,
      skill,
      issueMonth,
      issueYear,
      templateID: currentTemplate.id,
      templateSnapshot: currentTemplate,
      placeholderValues: p.values
    };

    try {
      const res = await fetch("/.netlify/functions/issue-badge", {
        method: "POST",
        headers: getHeaders(), // Secure request
        body: JSON.stringify(payload)
      });
      
      // If the token is invalid/expired, this breaks the loop immediately
      if (handleApiError(res)) return; 

      if (res.ok) successCount++;
    } catch (err) {
      console.error(`Failed to issue badge for ${p.email}:`, err);
    }
  }

  alert(`Successfully issued ${successCount} out of ${queue.length} badges!`);
  
  // Reset Queue
  queue = [];
  renderQueue();
  
  btn.innerText = "🚀 Issue All Badges in Queue";
  btn.disabled = false;
}
